
const P=window.TS_PROPERTIES||[];
const isSub=location.pathname.includes('/provinces/');
const prefix=isSub?'../':'';
function card(p){return `<article class="card"><img loading="lazy" src="${p.image}" alt="${p.name}"><div class="card-body"><div class="location">${p.city}, ${p.province}</div><h3>${p.name}</h3><div class="meta"><span>Up to ${p.capacity} delegates</span><span>${p.type}</span></div><div class="card-actions"><a class="btn" href="${prefix}property.html?id=${p.id}">View property</a><a class="btn btn-outline" href="${prefix}provinces/${slug(p.province)}.html">${p.province}</a></div></div></article>`}
function slug(s){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
const hp=document.querySelector('#home-provinces');if(hp){[...new Set(P.map(x=>x.province))].sort().forEach(pr=>{const n=P.filter(x=>x.province===pr).length;hp.innerHTML+=`<a class="province-card" href="provinces/${slug(pr)}.html"><p class="eyebrow">Province</p><h3>${pr}</h3><strong>${n} properties →</strong></a>`})}
const feat=document.querySelector('#featured');if(feat)feat.innerHTML=P.slice(0,6).map(card).join('');
const pg=document.querySelector('#province-grid');if(pg){const list=P.filter(x=>x.province===pg.dataset.province);pg.innerHTML=list.map(card).join('');document.querySelector('#count').textContent=`${list.length} properties in ${pg.dataset.province}`}
const grid=document.querySelector('#property-grid');if(grid){const province=document.querySelector('#province'),city=document.querySelector('#city'),cap=document.querySelector('#capacity'),type=document.querySelector('#type');[...new Set(P.map(x=>x.province))].sort().forEach(v=>province.innerHTML+=`<option>${v}</option>`);function cities(){city.innerHTML='<option value="">All locations</option>';[...new Set(P.filter(x=>!province.value||x.province===province.value).map(x=>x.city))].sort().forEach(v=>city.innerHTML+=`<option>${v}</option>`)}function render(){let r=P.filter(x=>(!province.value||x.province===province.value)&&(!city.value||x.city===city.value)&&(!cap.value||x.capacity>=+cap.value)&&(!type.value||x.type===type.value));grid.innerHTML=r.map(card).join('');document.querySelector('#count').textContent=`${r.length} properties found`}province.onchange=()=>{cities();render()};document.querySelector('#filters').onsubmit=e=>{e.preventDefault();render()};cities();render()}
if(document.querySelector('#property-name')){const id=new URLSearchParams(location.search).get('id'),p=P.find(x=>x.id===id)||P[0];document.title=p.name+' | TS Group Africa';document.querySelector('#property-name').textContent=p.name;document.querySelector('#property-province').textContent=p.province;document.querySelector('#property-location').textContent=p.city;document.querySelector('#property-image').src=p.image;document.querySelector('#property-image').alt=p.name;document.querySelector('#property-description').textContent=p.description;document.querySelector('#property-type').textContent=p.type;document.querySelector('#property-capacity').textContent=p.capacity+' delegates';document.querySelector('#property-amenities').innerHTML=p.amenities.map(a=>`<span>${a}</span>`).join('');const l=document.querySelector('#province-link');l.textContent=p.province;l.href=`provinces/${slug(p.province)}.html`}
